[package]
name = "h-mail-client"
version = "0.1.0"
edition = "2024"

[dependencies]
h-mail = { path="../h-mail" }
reqwest = { version = "0.12.22", features = ["json"] }
tokio = "1.46.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
rsa = "0.9.8"
sha2 = "0.10.9"
